
import { Language, LightingTime, SunDirection, WeatherCondition, MasterStyle } from './types';

export const TRANSLATIONS = {
  [Language.English]: {
    appTitle: "EDEN AI Architect",
    appSubtitle: "Your Rendering Assistant",
    badge: "Prompt Tool",
    sceneParams: "Scene Parameters",
    promptInputLabel: "Vision & Description",
    promptInputPlaceholder: "Describe the desired outcome (e.g., 'A futuristic museum with curved glass facade, surrounded by a park')...",
    tagsLabel: "Quick Tags",
    aiEnhance: "AI Enhance",
    optimizing: "Optimizing...",
    lighting: "Lighting Time",
    sunDirection: "Sun Direction",
    weather: "Weather",
    siteContext: "Site Context",
    aerialLabel: "Aerial / Background",
    aerialSub: "(Optional) For composites",
    styleRef: "Style References",
    materialLabel: "Material & Mood",
    materialSub: "(Recommended) Upload multiple",
    mainGeo: "Main Geometry",
    required: "REQUIRED",
    sketchLabel: "Upload Sketch / 3D Blockout",
    sketchNote: "The AI will analyze the geometry from this image strictly. Ensure lines are clear.",
    generateBtn: "Initialize Rendering",
    analyzing: "Analyzing Geometry...",
    generatingImage: "Raytracing...",
    resultReady: "Visualization Ready",
    copy: "Copy Text",
    copied: "Copied",
    copyNote: "Copy this prompt into Midjourney, Stable Diffusion, or your renderer of choice.",
    uploadClick: "Click to upload",
    uploadNote: "JPG, PNG up to 10MB",
    addMore: "Add more",
    errorSketch: "Main Sketch is required.",
    errorGeneric: "An unexpected error occurred.",
    imageResult: "AI Visualization",
    download: "Download",
    editMode: "Edit Image",
    brushSize: "Brush Size",
    clearMask: "Clear Mask",
    undo: "Undo",
    redo: "Redo",
    editPromptPlaceholder: "Describe what to change in the highlighted area...",
    applyEdit: "Apply Changes",
    cancelEdit: "Cancel",
    processingEdit: "Processing Edit...",
    historyLabel: "Generation History",
    historyEmpty: "No history yet. Generate an image to save it here.",
    zoomIn: "Click to Zoom",
    close: "Close",
    masterFilterLabel: "Master Photography Filters",
    masterReFilterLabel: "Master Re-Filter",
    adLabel: "Recommended Items",
    adTitle: "3D Modeling & Rendering Services",
    adDesc: "Professional 3D modeling, drafting, and high-quality rendering production.",
    visitShop: "Shop Now",
    [LightingTime.Sunny]: "Sunny",
    [LightingTime.Sunset]: "Sunset",
    [LightingTime.Night]: "Night",
    [SunDirection.TopLeft]: "Top-Left",
    [SunDirection.TopRight]: "Top-Right",
    [SunDirection.BottomLeft]: "Bottom-Left",
    [SunDirection.BottomRight]: "Bottom-Right",
    [WeatherCondition.Clear]: "Clear",
    [WeatherCondition.Cloudy]: "Cloudy",
    [WeatherCondition.Rain]: "Rain",
    [WeatherCondition.Snow]: "Snow",
    [WeatherCondition.ThickFog]: "Thick Fog",
    [WeatherCondition.LightMist]: "Light Mist",
  },
  [Language.ChineseTraditional]: {
    appTitle: "EDEN 你的建築渲染幫手",
    appSubtitle: "AI 建築視覺化引擎",
    badge: "提示詞工程工具",
    sceneParams: "場景參數設定",
    promptInputLabel: "設計願景與描述",
    promptInputPlaceholder: "描述您想要的成果（例如：「一座具有弧形玻璃幕牆的未來感博物館，被公園環繞」）...",
    tagsLabel: "常用標籤",
    aiEnhance: "AI 優化提示詞",
    optimizing: "優化中...",
    lighting: "光照時間",
    sunDirection: "太陽方位",
    weather: "天氣狀況",
    siteContext: "基地環境",
    aerialLabel: "空拍圖 / 背景",
    aerialSub: "（選填）用於合成",
    styleRef: "風格參考圖",
    materialLabel: "材質與氛圍",
    materialSub: "（推薦）上傳多張",
    mainGeo: "主體幾何",
    required: "必填",
    sketchLabel: "上傳草圖 / 3D 模型",
    sketchNote: "AI 將嚴格分析此圖像的幾何形狀。請確保線條清晰。",
    generateBtn: "啟動渲染程序",
    analyzing: "分析幾何中...",
    generatingImage: "光線追蹤運算中...",
    resultReady: "視覺化已就緒",
    copy: "複製文字",
    copied: "已複製",
    copyNote: "將此提示詞複製到 Midjourney、Stable Diffusion 或您選擇的渲染器中。",
    uploadClick: "點擊上傳",
    uploadNote: "JPG, PNG 最大 10MB",
    addMore: "新增更多",
    errorSketch: "主體草圖為必填項目。",
    errorGeneric: "發生未預期的錯誤。",
    imageResult: "AI 渲染預覽",
    download: "下載圖片",
    editMode: "局部修改",
    brushSize: "筆刷大小",
    clearMask: "清除選取",
    undo: "復原",
    redo: "重做",
    editPromptPlaceholder: "描述要如何在選取區域進行修改...",
    applyEdit: "套用修改",
    cancelEdit: "取消",
    processingEdit: "處理修改中...",
    historyLabel: "生成歷史紀錄",
    historyEmpty: "尚無紀錄。生成的圖像將會儲存在這裡。",
    zoomIn: "點擊放大檢視",
    close: "關閉",
    masterFilterLabel: "大師級攝影濾鏡",
    masterReFilterLabel: "大師再濾鏡",
    adLabel: "好物推薦",
    adTitle: "3d建模 模型 建模 3d繪圖 效果圖製作",
    adDesc: "專業3D建模、代工繪圖與高擬真效果圖製作服務。",
    visitShop: "前往賣場",
    [LightingTime.Sunny]: "晴天",
    [LightingTime.Sunset]: "日落",
    [LightingTime.Night]: "夜晚",
    [SunDirection.TopLeft]: "左上",
    [SunDirection.TopRight]: "右上",
    [SunDirection.BottomLeft]: "左下",
    [SunDirection.BottomRight]: "右下",
    [WeatherCondition.Clear]: "晴朗",
    [WeatherCondition.Cloudy]: "多雲",
    [WeatherCondition.Rain]: "雨天",
    [WeatherCondition.Snow]: "雪天",
    [WeatherCondition.ThickFog]: "濃霧",
    [WeatherCondition.LightMist]: "薄霧",
  },
  [Language.Japanese]: {
    appTitle: "EDEN 建築レンダリング",
    appSubtitle: "AIビジュアライゼーション",
    badge: "プロンプト作成ツール",
    sceneParams: "シーンパラメータ",
    promptInputLabel: "ビジョンと説明",
    promptInputPlaceholder: "希望する結果を記述してください（例：「曲線的なガラスファサードを持つ未来的な博物館、公園に囲まれている」）...",
    tagsLabel: "クイックタグ",
    aiEnhance: "AI プロンプト最適化",
    optimizing: "最適化中...",
    lighting: "照明時間",
    sunDirection: "太陽の方向",
    weather: "天気",
    siteContext: "敷地コンテキスト",
    aerialLabel: "航空写真 / 背景",
    aerialSub: "（任意）合成用",
    styleRef: "スタイル参照",
    materialLabel: "素材とムード",
    materialSub: "（推奨）複数アップロード",
    mainGeo: "メイン形状",
    required: "必須",
    sketchLabel: "スケッチ / 3Dモデル",
    sketchNote: "AIはこの画像の形状を厳密に分析します。線が鮮明であることを確認してください。",
    generateBtn: "レンダリング開始",
    analyzing: "形状を分析中...",
    generatingImage: "レイトレーシング中...",
    resultReady: "生成完了",
    copy: "コピー",
    copied: "コピー完了",
    copyNote: "このプロンプトをMidjourney、Stable Diffusion、またはお好みのレンダラーにコピーしてください。",
    uploadClick: "クリックしてアップロード",
    uploadNote: "JPG, PNG 最大 10MB",
    addMore: "追加",
    errorSketch: "メインスケッチは必須です。",
    errorGeneric: "予期しないエラーが発生しました。",
    imageResult: "AIレンダリング",
    download: "ダウンロード",
    editMode: "部分編集",
    brushSize: "ブラシサイズ",
    clearMask: "マスク消去",
    undo: "元に戻す",
    redo: "やり直し",
    editPromptPlaceholder: "選択範囲の変更内容を記述...",
    applyEdit: "変更を適用",
    cancelEdit: "キャンセル",
    processingEdit: "編集処理中...",
    historyLabel: "生成履歴",
    historyEmpty: "履歴はありません。生成された画像はここに保存されます。",
    zoomIn: "クリックして拡大",
    close: "閉じる",
    masterFilterLabel: "マスターグレード写真フィルター",
    masterReFilterLabel: "マスター再フィルター",
    adLabel: "おすすめアイテム",
    adTitle: "3Dモデリング・レンダリング制作",
    adDesc: "プロフェッショナルな3Dモデリング、製図、高品質なパース制作。",
    visitShop: "ショップへ移動",
    [LightingTime.Sunny]: "晴れ",
    [LightingTime.Sunset]: "夕方",
    [LightingTime.Night]: "夜",
    [SunDirection.TopLeft]: "左上",
    [SunDirection.TopRight]: "右上",
    [SunDirection.BottomLeft]: "左下",
    [SunDirection.BottomRight]: "右下",
    [WeatherCondition.Clear]: "快晴",
    [WeatherCondition.Cloudy]: "曇り",
    [WeatherCondition.Rain]: "雨",
    [WeatherCondition.Snow]: "雪",
    [WeatherCondition.ThickFog]: "濃霧",
    [WeatherCondition.LightMist]: "薄霧",
  },
  [Language.Korean]: {
    appTitle: "EDEN 건축 렌더링 도우미",
    appSubtitle: "AI 시각화 엔진",
    badge: "프롬프트 엔지니어링 도구",
    sceneParams: "장면 매개변수",
    promptInputLabel: "비전 및 설명",
    promptInputPlaceholder: "원하는 결과물을 설명하세요 (예: '곡선형 유리 파사드가 있는 미래지향적인 박물관, 공원으로 둘러싸임')...",
    tagsLabel: "빠른 태그",
    aiEnhance: "AI 프롬프트 최적화",
    optimizing: "최적화 중...",
    lighting: "조명 시간",
    sunDirection: "태양 방향",
    weather: "날씨",
    siteContext: "사이트 컨텍스트",
    aerialLabel: "항공 사진 / 배경",
    aerialSub: "(선택 사항) 합성용",
    styleRef: "스타일 참조",
    materialLabel: "재료 및 분위기",
    materialSub: "(권장) 여러 장 업로드",
    mainGeo: "메인 지오메트리",
    required: "필수",
    sketchLabel: "스케치 / 3D 모델 업로드",
    sketchNote: "AI가 이 이미지의 지오메트리를 엄격하게 분석합니다. 선이 명확한지 확인하세요.",
    generateBtn: "렌더링 시작",
    analyzing: "지오메트리 분석 중...",
    generatingImage: "레이트레이싱 중...",
    resultReady: "시각화 완료",
    copy: "텍스트 복사",
    copied: "복사됨",
    copyNote: "이 프롬프트를 Midjourney, Stable Diffusion 또는 선택한 렌더러에 복사하세요.",
    uploadClick: "업로드하려면 클릭",
    uploadNote: "JPG, PNG 최대 10MB",
    addMore: "더 추가",
    errorSketch: "메인 스케치는 필수입니다.",
    errorGeneric: "예기치 않은 오류가 발생했습니다.",
    imageResult: "AI 렌더링",
    download: "다운로드",
    editMode: "부분 편집",
    brushSize: "브러시 크기",
    clearMask: "마스크 지우기",
    undo: "실행 취소",
    redo: "다시 실행",
    editPromptPlaceholder: "선택한 영역을 어떻게 변경할지 설명하세요...",
    applyEdit: "변경 적용",
    cancelEdit: "취소",
    processingEdit: "편집 처리 중...",
    historyLabel: "생성 기록",
    historyEmpty: "기록이 없습니다. 생성된 이미지가 여기에 저장됩니다.",
    zoomIn: "클릭하여 확대",
    close: "닫기",
    masterFilterLabel: "마스터 그레이드 사진 필터",
    masterReFilterLabel: "마스터 재필터",
    adLabel: "추천 아이템",
    adTitle: "3D 모델링 및 렌더링 제작",
    adDesc: "전문 3D 모델링, 제도 및 고품질 렌더링 제작 서비스.",
    visitShop: "상점 방문",
    [LightingTime.Sunny]: "맑음",
    [LightingTime.Sunset]: "일몰",
    [LightingTime.Night]: "밤",
    [SunDirection.TopLeft]: "왼쪽 상단",
    [SunDirection.TopRight]: "오른쪽 상단",
    [SunDirection.BottomLeft]: "왼쪽 하단",
    [SunDirection.BottomRight]: "오른쪽 하단",
    [WeatherCondition.Clear]: "쾌청",
    [WeatherCondition.Cloudy]: "흐림",
    [WeatherCondition.Rain]: "비",
    [WeatherCondition.Snow]: "눈",
    [WeatherCondition.ThickFog]: "짙은 안개",
    [WeatherCondition.LightMist]: "옅은 안개",
  }
};

export const ARCH_TAGS = {
    [Language.English]: {
        Styles: ["Modern", "Minimalist", "Brutalist", "Industrial", "Parametric", "Scandinavian", "Traditional", "Futuristic"],
        Materials: ["Concrete", "Glass Facade", "Timber", "Red Brick", "Corten Steel", "White Stucco", "Stone"],
        Mood: ["Photorealistic", "Cinematic", "Warm Lighting", "Overgrown", "Cyberpunk", "Eco-friendly", "Luxury"],
    },
    [Language.ChineseTraditional]: {
        Styles: ["現代主義", "極簡主義", "清水模(粗獷主義)", "工業風", "參數化設計", "北歐風", "傳統建築", "未來感"],
        Materials: ["混凝土", "玻璃幕牆", "木格柵", "紅磚", "耐候鋼", "白色塗料", "石材"],
        Mood: ["照片級真實", "電影感", "溫暖光影", "綠植共生", "賽博龐克", "生態友善", "奢華感"],
    },
    [Language.Japanese]: {
        Styles: ["モダン", "ミニマリスト", "ブルータリズム", "インダストリアル", "パラメトリック", "スカンジナビア", "伝統的", "未来的"],
        Materials: ["コンクリート", "ガラスファサード", "木材", "赤レンガ", "コールテン鋼", "漆喰", "石材"],
        Mood: ["フォトリアル", "シネマティック", "暖かい照明", "緑化", "サイバーパンク", "エコフレンドリー", "ラグジュアリー"],
    },
    [Language.Korean]: {
        Styles: ["모던", "미니멀리스트", "브루탈리즘", "인더스트리얼", "파라메트릭", "스칸디나비아", "전통", "미래지향적"],
        Materials: ["콘크리트", "유리 파사드", "목재", "붉은 벽돌", "코르텐 강철", "화이트 스터코", "석재"],
        Mood: ["포토리얼리스틱", "시네마틱", "따뜻한 조명", "자연 친화적", "사이버펑크", "친환경", "럭셔리"],
    }
};

export const MASTER_STYLES: Record<Language, MasterStyle[]> = {
    [Language.English]: [
        { id: 'long_exposure', label: 'Long Exposure', prompt: 'MASTERPIECE, EXTREME LONG EXPOSURE PHOTOGRAPHY (30 seconds+). Silky smooth water effect, dramatic streaking clouds, perfect light trails. Tripod shot, ISO 50, f/16. Ethereal, dreamy atmosphere overriding reality.', icon: 'clock' },
        { id: 'bw_fine_art', label: 'Noir B&W', prompt: 'FINE ART B&W PHOTOGRAPHY. PURE MONOCHROME. NO COLOR. Intense high contrast, deep ink blacks, bright stark whites. Ansel Adams style. Dramatic shadows, structural clarity, abstract geometry. Film noir aesthetic.', icon: 'contrast' },
        { id: 'high_fashion', label: 'Vogue Editorial', prompt: 'HIGH FASHION EDITORIAL ARCHITECTURE. Sharp, vibrant, commercial aesthetic. Wallpaper* Magazine style. Perfect crystal clear blue sky, hyper-saturated colors, crisp shadows. Clean, luxury, expensive look. 8k resolution.', icon: 'star' },
        { id: 'cinematic_mood', label: 'Cyber Cinematic', prompt: 'DARK CINEMATIC MOOD. Blade Runner 2049 aesthetic. Volumetric fog, teal and orange color grading, neon accents, rainy reflections. Moody, mysterious, atmospheric. Anamorphic lens flares.', icon: 'film' },
        { id: 'blue_hour', label: 'Blue Hour', prompt: 'PERFECT BLUE HOUR PHOTOGRAPHY. Deep twilight blue sky. Warm artificial interior lights glowing (3200K) against cold exterior environment (8000K). Balanced exposure. Magical realism.', icon: 'moon' },
    ],
    [Language.ChineseTraditional]: [
        { id: 'long_exposure', label: '極致長曝光', prompt: 'MASTERPIECE, EXTREME LONG EXPOSURE PHOTOGRAPHY (30 seconds+). Silky smooth water effect, dramatic streaking clouds, perfect light trails. Tripod shot, ISO 50, f/16. Ethereal, dreamy atmosphere overriding reality.', icon: 'clock' },
        { id: 'bw_fine_art', label: '黑白藝術', prompt: 'FINE ART B&W PHOTOGRAPHY. PURE MONOCHROME. NO COLOR. Intense high contrast, deep ink blacks, bright stark whites. Ansel Adams style. Dramatic shadows, structural clarity, abstract geometry. Film noir aesthetic.', icon: 'contrast' },
        { id: 'high_fashion', label: 'Vogue 時尚風', prompt: 'HIGH FASHION EDITORIAL ARCHITECTURE. Sharp, vibrant, commercial aesthetic. Wallpaper* Magazine style. Perfect crystal clear blue sky, hyper-saturated colors, crisp shadows. Clean, luxury, expensive look. 8k resolution.', icon: 'star' },
        { id: 'cinematic_mood', label: '賽博電影感', prompt: 'DARK CINEMATIC MOOD. Blade Runner 2049 aesthetic. Volumetric fog, teal and orange color grading, neon accents, rainy reflections. Moody, mysterious, atmospheric. Anamorphic lens flares.', icon: 'film' },
        { id: 'blue_hour', label: '藍調時刻', prompt: 'PERFECT BLUE HOUR PHOTOGRAPHY. Deep twilight blue sky. Warm artificial interior lights glowing (3200K) against cold exterior environment (8000K). Balanced exposure. Magical realism.', icon: 'moon' },
    ],
    [Language.Japanese]: [
        { id: 'long_exposure', label: '長時間露光', prompt: 'MASTERPIECE, EXTREME LONG EXPOSURE PHOTOGRAPHY (30 seconds+). Silky smooth water effect, dramatic streaking clouds, perfect light trails. Tripod shot, ISO 50, f/16. Ethereal, dreamy atmosphere overriding reality.', icon: 'clock' },
        { id: 'bw_fine_art', label: 'モノクロ芸術', prompt: 'FINE ART B&W PHOTOGRAPHY. PURE MONOCHROME. NO COLOR. Intense high contrast, deep ink blacks, bright stark whites. Ansel Adams style. Dramatic shadows, structural clarity, abstract geometry. Film noir aesthetic.', icon: 'contrast' },
        { id: 'high_fashion', label: 'ファッション誌風', prompt: 'HIGH FASHION EDITORIAL ARCHITECTURE. Sharp, vibrant, commercial aesthetic. Wallpaper* Magazine style. Perfect crystal clear blue sky, hyper-saturated colors, crisp shadows. Clean, luxury, expensive look. 8k resolution.', icon: 'star' },
        { id: 'cinematic_mood', label: 'サイバー映画風', prompt: 'DARK CINEMATIC MOOD. Blade Runner 2049 aesthetic. Volumetric fog, teal and orange color grading, neon accents, rainy reflections. Moody, mysterious, atmospheric. Anamorphic lens flares.', icon: 'film' },
        { id: 'blue_hour', label: 'ブルーアワー', prompt: 'PERFECT BLUE HOUR PHOTOGRAPHY. Deep twilight blue sky. Warm artificial interior lights glowing (3200K) against cold exterior environment (8000K). Balanced exposure. Magical realism.', icon: 'moon' },
    ],
    [Language.Korean]: [
        { id: 'long_exposure', label: '장노출 마스터', prompt: 'MASTERPIECE, EXTREME LONG EXPOSURE PHOTOGRAPHY (30 seconds+). Silky smooth water effect, dramatic streaking clouds, perfect light trails. Tripod shot, ISO 50, f/16. Ethereal, dreamy atmosphere overriding reality.', icon: 'clock' },
        { id: 'bw_fine_art', label: '흑백 파인아트', prompt: 'FINE ART B&W PHOTOGRAPHY. PURE MONOCHROME. NO COLOR. Intense high contrast, deep ink blacks, bright stark whites. Ansel Adams style. Dramatic shadows, structural clarity, abstract geometry. Film noir aesthetic.', icon: 'contrast' },
        { id: 'high_fashion', label: 'Vogue 에디토리얼', prompt: 'HIGH FASHION EDITORIAL ARCHITECTURE. Sharp, vibrant, commercial aesthetic. Wallpaper* Magazine style. Perfect crystal clear blue sky, hyper-saturated colors, crisp shadows. Clean, luxury, expensive look. 8k resolution.', icon: 'star' },
        { id: 'cinematic_mood', label: '사이버 시네마틱', prompt: 'DARK CINEMATIC MOOD. Blade Runner 2049 aesthetic. Volumetric fog, teal and orange color grading, neon accents, rainy reflections. Moody, mysterious, atmospheric. Anamorphic lens flares.', icon: 'film' },
        { id: 'blue_hour', label: '블루 아워', prompt: 'PERFECT BLUE HOUR PHOTOGRAPHY. Deep twilight blue sky. Warm artificial interior lights glowing (3200K) against cold exterior environment (8000K). Balanced exposure. Magical realism.', icon: 'moon' },
    ]
};
